<?php /* @var $this Sirateck_Lemonwaymkt_Block_Account */ ?>
<div class="dashboard">
    <div class="page-title">
        <h1><?php echo $this->__('Lemonway payment') ?></h1>
    </div>
    <?php echo $this->getMessagesBlock()->toHtml() ?>
	<form action="<?php echo $this->getUrl('lemonwaymkt/account/doMoneyoutPost')?>" method="post" >
		<div class="fieldset">
			<h2 class="legend"><?php echo $this->__('Money out Informations') ?></h2>
			<ul class="messages">
				<li class="notice-msg">
					<ul>
						<li>				
							<?php echo $this->__('Your current balance: <b>%s</b>',$this->formatPrice($this->getWalletDetails()->wallet->getBal()))?>
						</li>
					</ul>
				</li>
			</ul>
			<ul class="form-list">
				<li class="wide">
                	<label for="iban_id" class="required"><?php echo $this->__('Ibans list')?></label>
	                <div class="input-box">
	                	<select id="iban_id" name="moneyout_data[iban_id]">
	                		<option value="0"><?php echo $this->__('Select a creditor account')?></option>
	                		<?php foreach ($this->getIbans() as $iban):?>
	                			<option value="<?php echo $iban->getId()?>"><?php echo $iban->getIban()?></option>
	                		<?php endforeach;?>
	                	</select>
	                </div>
            	</li>
				<li class="wide">
                	<label for="amount_to_pay" class="required"><?php echo $this->__('Amount to transfert')?></label>
	                <div class="input-box">
	                	<input type="text" class="input-text required" id="amount_to_pay" name="moneyout_data[amount_to_pay]" value="" >
	                </div>
            	</li>
			</ul>
		</div>
		<div class="buttons-set">
        	<p class="back-link"><a href="<?php echo $this->getUrl('lemonwaymkt/account/') ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
        	<button type="submit" class="button" title="<?php echo $this->__('Do my money out') ?>"><span><span><?php echo $this->__('Do my money out') ?></span></span></button>
    </div>
	</form>

</div>